server:
  port: 8084

spring:
  application:
    name: message-service
  
  # MongoDB configuration
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DBNAME:ChatApp}
  

# Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
  instance:
    hostname: ${HOSTNAME:localhost}
    prefer-ip-address: true

# Application specific settings
chatroomApp:
  pageable:
    DefaultPageSize_Messages: 10

# Logging configuration
logging:
  level:
    com.devStudy.chatapp.message: DEBUG
    org.springframework.data.mongodb: DEBUG