name: MyChatApp

networks:
  chatapp-network:
    driver: bridge
  middleware-network:
    driver: bridge

services:
  frontend:
    build: ./ChatApp_Frontend
    container_name: chatapp-frontend
    ports:
      - "4200:80"
    networks:
      - chatapp-network
  
  postgres:
    image: postgres:latest
    container_name: chatapp-postgres
    environment:
      - POSTGRES_USER=user #  your postgres username
      - POSTGRES_PASSWORD=password # your postgres password
      - POSTGRES_DB=chatAppDB
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./SQL-Scripts:/docker-entrypoint-initdb.d
    networks:
      - middleware-network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: chatapp-mongodb
    volumes:
      - ./mongodb-data:/data/db
    networks:
      - middleware-network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:latest
    container_name: chatapp-rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin # your rabbitmq username
      - RABBITMQ_DEFAULT_PASS=admin # your rabbitmq password
    networks:
      - middleware-network
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: chatapp-redis
    networks:
      - middleware-network
    restart: unless-stopped

  backend:
    build: ./ChatApp_Backend
    container_name: chatapp-backend
    depends_on:
      - postgres
      - mongodb
      - redis
      - rabbitmq
    entrypoint:
      - ./wait-for-it.sh
      - postgres:5432
      - --timeout=60
      - --strict
      - --
      - ./wait-for-it.sh
      - mongodb:27017
      - --timeout=60
      - --strict
      - --
      - ./wait-for-it.sh
      - redis:6379
      - --timeout=60
      - --strict
      - --
      - ./wait-for-it.sh
      - rabbitmq:5672
      - --timeout=60
      - --strict
      - --
      - java
      - -jar
      - chatApp.jar
    environment:
      - DB_HOST=postgres
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - MONGO_HOST=mongodb
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin
      - FRONT_URL=http://localhost:4200
    networks:
      - chatapp-network
      - middleware-network
    