server:
  port: 8083

spring:
  application:
    name: crud-service
    
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/chatAppDB
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:admin}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:crud-service}

# 应用配置
chatroomApp:
  pageable:
    DefaultPageSize_Chatrooms: 5
    DefaultPageSize_Users: 5

logging:
  level:
    com.devStudy.chatapp.crud: DEBUG