spring:
  # PostgreSQL 数据源配置
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:chatAppDB}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:721215}
    driver-class-name: org.postgresql.Driver
  
  # JPA 配置
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  
  # MongoDB 配置
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DBNAME:ChatApp}
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  
  # MVC 配置
  mvc:
    hidden method:
      filter:
        enabled: true
  
  # 邮件配置
  mail:
    host: smtp.your-email-provider.com
    port: 000 # your email provider port
    username: your-email-address@mail.com
    password: your-generated-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # RabittMQ 配置
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:admin}

# 应用自定义配置
chatroomApp:
  FrontEndURL: ${FRONT_URL:http://localhost:4200}
  CHAT_ENDPOINT: ${CHAT_ENDPOINT:/ws/chatroom/{chatroomId}/user/{userId}}
  VERIFICATION_CODE_LOGIN_ENDPOINT: ${VERIFICATION_CODE_LOGIN_ENDPOINT:/api/login/verification-code-process}
  MAX_FAILED_ATTEMPTS: 5
  CHAT_SESSION_EXPIRY: 86400
  pageable:
    DefaultPageSize_Users: 5
    DefaultPageSize_Chatrooms: 5
    DefaultPageSize_Messages: 10
  redis:
    expirationTime: 300
  jwt:
    secret: dGhpcyBpcyBhIHRlc3Qgc2VjcmV0IGtleSBmb3IgZ2VuZXJhdGUgand0IHRva2Vucw==
    resetPwdTokenExpirationTime: 30
    loginTokenExpirationTime: 120
  rememberMe:
    key: remerber-me
    expirationTime: 604800

server:
  port: 53050
