server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      # 开启服务发现路由
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      
      routes:
        # 认证服务路由
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        
        # CRUD服务路由 (包含用户查询和聊天室管理)
        - id: crud-service-users
          uri: lb://crud-service
          predicates:
            - Path=/api/users/**
          filters:
            - AuthenticationGatewayFilter  # 添加认证过滤器
        
        - id: crud-service-chatrooms
          uri: lb://crud-service
          predicates:
            - Path=/api/chatrooms/**
          filters:
            - AuthenticationGatewayFilter  # 添加认证过滤器
        
        # 消息服务路由
        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/api/messages/**
          filters:
            - StripPrefix=2  # 去掉 /api/messages 前缀
            - AuthenticationGatewayFilter  # 添加认证过滤器
        
        # WebSocket网关路由
        - id: websocket-gateway
          uri: lb://websocket-gateway
          predicates:
            - Path=/ws/**

      # 全局CORS配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600

  # Redis配置（用于限流）
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

# Eureka客户端配置
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
    registry-fetch-interval-seconds: 30
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: false
    hostname: ${HOSTNAME:api-gateway}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

# 监控端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

# 日志配置
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.netflix.eureka: INFO

# JWT配置
chatroomApp:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970